export enum actionTypes {
  LOAD_CARS = "LOAD_CARS",

  SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER",

  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT = "LOGOUT",
  LOGIN = "LOGIN",
  LOGIN_FAIL = "LOGIN_FAIL",
}
